# Change these first
owner: juanLabonia # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Nodo
    url: https://www.101si.com.ar/
  - name: Ofishop
    url: https://ofishop.com/
  - name: EDGAR
    url: https://www.edgar.com.ar/
  - name: ARBA COT
    url: https://cot.arba.gov.ar/TransporteBienes/SeguridadCliente/presentarRemitos.do
  - name: Tango
    method: POST
    url: https://tiendas.axoft.com/api/Aperture/dummy
    expectedStatusCodes:
      - 411
  - name: C.P.G.S.M.
    url: http://cpgsm.101si.com.ar:8001
  
  - name: AIT
    url: https://45.232.164.238:4434/

assigness:
  - juanLabonia
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  
  baseUrl: /uptime
  
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** Proyectó impulsado completamente por GitHub."
  introMessage: Esta página muestra en **tiempo real** los estados de diferentes servicios, esto es proporcionado por GitHub.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

